#!/bin/bash
#
# ----------------------------------------------------------------------------------------------------
#
# Copyright (c) 2007, 2016, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
# ----------------------------------------------------------------------------------------------------

# Not all systems (e.g. Mac OS X) have 'python2' on the path.
type python2.7 >/dev/null 2>&1
if [ $? -eq 0 ]; then
    python_exe=python2.7
else
    type python2.6 >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        python_exe=python2.6
    else
        type python2 > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            python_exe=python2
        else
            python_exe=python
        fi
    fi
fi

$python_exe <<END
import sys
major, minor, micro, _, _ = sys.version_info
if major != 2 or (minor != 6 and minor != 7):
    raise SystemExit('The build scripts of Node.js require Python 2.6 or 2.7, not {0}.{1}.{2}'.format(major, minor, micro))
END
if [ $? -eq 0 ]; then
    echo "#### $python_exe ####"
    exec $python_exe "$@"
else
    exit 1
fi

#end of file
