#!/usr/bin/env bash

source="${BASH_SOURCE[0]}"
while [ -h "$source" ] ; do
    prev_source="$source"
    source="$(readlink "$source")";
    if [[ "$source" != /* ]]; then
        # if the link was relative, it was relative to where it came from
        dir="$( cd -P "$( dirname "$prev_source" )" && pwd )"
        source="$dir/$source"
    fi
done

bin_dir="$( cd -P "$( dirname "$source" )" && pwd )"
parent_dir="$( dirname "$bin_dir" )"

if [ ! -x "${parent_dir}/jvm/bin/java" ]; then
    echo "Error: ${parent_dir}/jvm/bin/java not found. $(basename "$0") is not available for the native standalone."
    exit 1
fi

if [ "${VERBOSE_GRAALVM_LAUNCHERS}" == "true" ]; then
    set -x
fi

exec "${parent_dir}/jvm/bin/java" "-p" "${parent_dir}/modules" "-m" "org.graalvm.maven.downloader/org.graalvm.maven.downloader.Main" "$@"
